config:
  default: true
  line-length: false
  no-duplicate-heading: false
  table-column-style: false
gitignore: true
globs:
  - '**/*.md'
ignores:
  - dist/**
  - .astro/**
  - .agents/**
  - .claude/**
  - .github/**
  - .netlify/**
  - node_modules/**
noBanner: true
noProgress: true
